### ISSUE TITLE
[PICTURES-002]: create PR template

### ISSUE THREAD

**Issue by mskalandunas** [mskalandunas/pictures#2]
This is just to automate the review process a little bit.

* Add a summary section
* Add reviewers (dzwell + mskalandunas)

More info:
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by DZwell** [comment]
Any preference as to where the template is stored? According to the docs they can be stored in the root dir (either hidden or not) or in some other directory.

**Comment by mskalandunas** [comment]
Root did is perfect.
